# Generated by Django 3.0.8 on 2020-10-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
